require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - tmp/**/*

# Disabled cops

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Rails/FilePath:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false

# Modified cops

Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  Enabled: true
  EnforcedStyle: double_quotes

Layout/AccessModifierIndentation:
  Description: Indent private/protected/public as deep as method definitions
  Enabled: true
  EnforcedStyle: outdent

Style/Alias:
  Description: Use alias_method instead of alias in a class or module body.
  EnforcedStyle: prefer_alias_method

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/HashSyntax:
  Description: 'Prefer Ruby 1.8 hash syntax { :a => 1, :b => 2 } over 1.9 syntax { a: 1, b: 2 }.'
  Enabled: true
  EnforcedStyle: hash_rockets

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    default: '()'
    '%i':    '()'
    '%I':    '()'
    '%r':    '{}'
    '%w':    '()'
    '%W':    '()'
